const nonBlackICE = {
    hellbolt:{
      name: 'Hellbolt',
      progClass: 'Anti-NR Attacker',
      atk: 2,
      def: 0,
      rez: 0,
      effect:"2d6 DMG => NR:BRAIN. If [CD =/= Insulated] => CD & Clothes catch FIRE.  2 DMG => HP per Turn until NR takes MEAT ACTION=>put self out. [CANNOT STACK]",
      thumbURL: 'https://media1.giphy.com/media/VG8Dto0bkHDUdVYZrj/giphy.gif?cid=790b761157e585d5010fef2871c43539e88dd370ed006310&rid=giphy.gif&ct=g',
      actionLabel: 'BRAIN DMG',
      actionId: 'hellbolt_action',
      },
    banhammer:{
      name: 'Banhammer',
      progClass: 'Anti-PRGRM Attacker',
      atk: 1,
      def: 0,
      rez: 0,
      effect:" 3d6 REZ => Non-BlackICE PRGRM, or 2d6 REZ => BlackICE PRGRM. ",
      thumbURL: 'https://i.imgur.com/azCR8D1.gif',
      actionLabel: ['ATK Non-BlackICE PRGRM', 'ATK BlackICE PRGRM'],
      actionId: 'banhammer_action',
    },
    sword: {
      name: 'Sw0rd',
      progClass: 'Anti-PRGRM Attacker',
      atk: 1,
      def: 0,
      rez: 0,
      effect:" 3d6 REZ => BlackICE PRGRM, or 2d6 REZ => Non-BlackICE PRGRM. ",
      thumbURL: 'https://c.tenor.com/fQD5fvkp8HwAAAAC/sawa-yukimura-sawa.gif',
      actionLabel: ['ATK Non-BlackICE PRGRM', 'ATK BlackICE PRGRM'],
      actionId: 'sword_action',
    },
    deckkrash:{
      name: 'DeckKRASH',
      progClass: 'Anti-NR Attacker',
      atk: 0,
      def: 0,
      rez: 0,
      effect:"3d6 DMG => NR:BRAIN. NR forcibly and unsafely JACKED OUT of current RUN. NR suffers DMG of ALL REZZD PRGRMS encountered.",
      thumbURL: 'https://c.tenor.com/y33r5eXsELUAAAAd/serial-experiments-lain-lain.gif',
    },
    nervescrub:{
      name: 'Nervescrub',
      progClass: 'Anti-NR Attacker',
      atk: 0,
      def: 0,
      rez: 0,
      effect:"NR's INT, REF, & DEX -1d6 for 1 hr (minimum 1).",
      thumbURL: 'https://c.tenor.com/RliaDiLzcnEAAAAC/serial-experiments-lain-lain.gif',
      actionLabel: 'BRAIN DMG',
      actionId: 'nervescrub_action'  
    },
    poisonflatline:{
      name: 'Poison Flatline',
      progClass: 'Anti-NR Attacker',
      atk: 0,
      def: 0,
      rez: 0,
      effect:"DESTROY 1 PRGRM on NR's CD @ RANDOM.",
      thumbURL: 'https://64.media.tumblr.com/cac533ba2d76d04bb3af42a8836a41da/tumblr_pm5yokAOZU1r6xm5co1_1280.gif',
      actionLabel: 'D-REZ Roulette',
      actionId: 'poisonflatline_action'
    },
    superglue: {
      name: 'Superglue',
      progClass: 'Anti-NR Attacker',
      atk: 2,
      def: 0,
      rez: 0,
      effect:"NR cannot MOVE deeper into the Architecture or JACK OUT safely until NEXT TURN (Can still perform unsafe Jack Out).",
      thumbURL: 'https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fphotos%2Fimages%2Fnewsfeed%2F001%2F135%2F770%2Fb2d.gif',
      actionLabel: 'Rounds',
      actionId: 'superglue_action' 
    },
    vrizzbolt: {
      name: 'Vrizzbolt',
      progClass: 'Anti-NR Attacker',
      atk: 1,
      def: 0,
      rez: 0,
      effect:"1d6 DMG => NR:BRAIN. -1 total NET ACTIONS on their next Turn (minumum 2).",
      thumbURL: 'https://78.media.tumblr.com/179cd9ffde8e8a3371be473717b958c5/tumblr_pau1xuwBQ41whahvko1_540.gif',
      actionLabel: 'BRAIN DMG',
      actionId: 'vrizzbolt_action'  
    },
    eraser: {
      name: 'Eras3r',
      progClass: 'Booster',
      atk: 0,
      def: 0,
      rez: 7,
      effect:"+2 CLOAK CHECK as long as this PRGRM = REZZD. ",
      thumbURL: 'https://64.media.tumblr.com/03f3571855f3b3c33ca75149bb42fdc3/5c196d8fe68c385e-b3/s500x750/821694d4b89c20d2b8865bb0aa4b457b38d4e583.gif',
      actionLabel: 'Enhanced Cloak',
      actionId: 'eraser_action'  
    },
    seeya:{
      name: 'See Ya',
      progClass: 'Booster',
      atk: 0,
      def: 0,
      rez: 7,
      effect:"+2 PATHFINDER CHECK as long as this PRGRM = REZZD. ",
      thumbURL: 'https://media0.giphy.com/media/2m1YQuAdhvG0q6HBab/200w.gif?cid=82a1493b5ctoh9g4vrx0qutqy0xbimorkvsewn1p9wv3ocpe&rid=200w.gif&ct=g',
      actionLabel: 'Enhanced Pathfinder',
      actionId: 'seeya_action'
    },
    speedygonzalvez: {
      name: 'Sp33dy G0nzalvez',
      progClass: 'Bosster',
      atk: 0,
      def: 0,
      rez: 7,
      effect:" +@ SPEED as long as this PRGRM = REZZD. ",
      thumbURL: 'https://i.pinimg.com/originals/dd/b7/d2/ddb7d26375807f772c47b7df57a15395.gif',
      actionLabel: 'SPD Boost',
      actionId: 'speedygonzalvez_action'  
    },
    worm: {
      name: 'Worm',
      progClass: 'Booster',
      atk: 0,
      def: 0,
      rez: 7,
      effect:"+2 BACKDOOR CHECKS as long as this PRGRM = REZZD. ",
      thumbURL: 'https://monophy.com/media/40DRc0W00UbgQ/monophy.gif',
      actionLabel: 'Enhanced Backdoor',
      actionId: 'worm_action'
    },
    armor: {
      name: 'Arm0r',
      progClass: 'Defender',
      atk: 0,
      def: 0,
      rez: 7,
      effect:"-4 BRAIN DMG you would receive as long as this PRGRM = REZZD. ",
      thumbURL: 'https://i.pinimg.com/originals/a8/07/f5/a807f5da6c07679020f90e6925bdbc1c.gif',
    },
    flak: {
      name: 'Flak',
      progClass: 'Defender',
      atk: 0,
      def: 0,
      rez: 7,
      effect:"All Non-BlackICE Attacker PRGRMs RUN against you: ATK = 0 as long as this PRGRM = REZZD. Only 1 of this PRGRM can be REZZD at a time. Can only be used 1x per RUN. ",
      thumbURL: 'https://i.pinimg.com/originals/97/ac/b4/97acb42cbfd990000954aef7954c497c.gif', 
    },
    shield: {
      name: 'Shi3ld',
      progClass: 'Defender',
      atk: 0,
      def: 0,
      rez: 7,
      effect:" Stops FIRST successful Non-BlackICE PRGRM Effect dealing BRAIN DMG. After STOPPING DMG, Shi3ld DREZZS. Only 1 copy of this PRGRM can be REZZD @ a time. Each copy of this PRGRM can only be used 1x per RUN. ",
      thumbURL: 'https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F7d5c5775-3fe7-4b55-afc7-73b5330e2e4c_720x720.gif',
    }
  }