const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const playerCharacter = new Schema({
  userID: String,
  guildID: String,
  username: String,
  characterName: String,
  characterImgUrl: String,
  hp: [Number, Number],
  weaponDrawn: String,
  role: {
    name: String,
    ability: String,
    rank: Number,
  },
  humanity: [Number, Number],
  seriouslyWounded: String,
  criticalInjuries: [String],
  addictions: [String],
  stats: {
    int: Number,
    ref: Number,
    dex: Number,
    tech: Number,
    cool: Number,
    will: Number,
    luck: [Number, Number],
    move: Number,
    body: Number,
    emp: [Number, Number],
  },
  skills: {
    concentration: Number,
    "conceal/reveal_object": Number,
    lip_reading: Number,
    perception: Number,
    tracking: Number,
    athletics: Number,
    contortionist: Number,
    dance: Number,
    endurance: Number,
    "resist_torture/drugs": Number,
    stealth: Number,
    drive_land_vehicle: Number,
    pilot_air_vehicle: Number,
    pilot_sea_vehicle: Number,
    riding: Number,
    accounting: Number,
    animal_handling: Number,
    bureaucracy: Number,
    business: Number,
    composition: Number,
    criminology: Number,
    cryptography: Number,
    deduction: Number,
    education: Number,
    gamble: Number,
    language: { streetslang: Number },
    library_search: Number,
    local_expert: { yourHome: Number },
    science: Object,
    tactics: Number,
    wilderness_survival: Number,
    brawling: Number,
    evasion: Number,
    martial_arts: Number,
    melee_weapons: Number,
    acting: Number,
    play_instrument: Object,
    archery: Number,
    autofire: Number,
    handgun: Number,
    heavy_weapons: Number,
    shoulder_arms: Number,
    bribery: Number,
    conversation: Number,
    human_perception: Number,
    interrogation: Number,
    persuasion: Number,
    personal_grooming: Number,
    streetwise: Number,
    trading: Number,
    "wardrobe&style": Number,
    air_vehicle_tech: Number,
    basic_tech: Number,
    cybertech: Number,
    demolititions: Number,
    electronics_security_tech: Number,
    first_aid: Number,
    forgery: Number,
    land_vehicle_tech: Number,
    "paint/draw/sculpt": Number,
    paramedic: Number,
    photography_film: Number,
    pick_lock: Number,
    pick_pocket: Number,
    sea_vehicle_tech: Number,
    weapons_tech: Number,
  },
  armor: {
  head: { name: String, sp: Number, penalty: String },
  body: { name: String, sp: Number, penalty: String },
  shield: { name: String, sp: Number, penalty: String },
  },
  weapons: [
    {
      ref: String,
      name: String,
      dmg: String,
      weaponType: String,
      ammo: Number,
      standardMag: Number,
      rof: Number,
      autofire: Boolean,
      skill: String,
      ammoType: String,
      ammoLoaded: String,
      rangeDV: Array,
    },
  ],
  ammo: [{ ref: String, name: String, ammoType: String, amt: Number, effect: String, ablate: Number }],
  cyberwear: Object,
  inventory: Object,
});

module.exports = mongoose.model("Character", playerCharacter);
