const mongoose = require("mongoose");

const Schema = mongoose.Schema;

const simplifiedCharacter = new Schema({
  userID: String,
  guildID: String,
  username: String,
  characterName: String,
  characterImgUrl: String,
  hp: [Number, Number],
  humanity: [Number, Number],
  role: String,
  rank: Number,
  criticalInjuries: [String],
  cyberarm: Boolean,
  stats: {
    int: [Number, Number],
    ref: [Number, Number],
    dex: [Number, Number],
    tech: [Number, Number],
    cool: [Number, Number],
    will: [Number, Number],
    luck: [Number, Number],
    move: [Number, Number],
    body: [Number, Number],
    emp: [Number, Number],
  },
  skills: {
    concentration: Number,
    "conceal/reveal_object": Number,
    lip_reading: Number,
    perception: Number,
    tracking: Number,
    athletics: Number,
    contortionist: Number,
    dance: Number,
    endurance: Number,
    "resist_torture/drugs": Number,
    stealth: Number,
    drive_land_vehicle: Number,
    pilot_air_vehicle: Number,
    pilot_sea_vehicle: Number,
    riding: Number,
    accounting: Number,
    animal_handling: Number,
    bureaucracy: Number,
    business: Number,
    composition: Number,
    criminology: Number,
    cryptography: Number,
    deduction: Number,
    education: Number,
    gamble: Number,
    language: { streetslang: Number },
    library_search: Number,
    local_expert: { yourHome: Number },
    science: Object,
    tactics: Number,
    wilderness_survival: Number,
    brawling: Number,
    evasion: Number,
    martial_arts: Number,
    melee_weapons: Number,
    acting: Number,
    play_instrument: Object,
    archery: Number,
    autofire: Number,
    handgun: Number,
    heavy_weapons: Number,
    shoulder_arms: Number,
    bribery: Number,
    conversation: Number,
    human_perception: Number,
    interrogation: Number,
    persuasion: Number,
    personal_grooming: Number,
    streetwise: Number,
    trading: Number,
    "wardrobe&style": Number,
    air_vehicle_tech: Number,
    basic_tech: Number,
    cybertech: Number,
    demolititions: Number,
    electronics_security_tech: Number,
    first_aid: Number,
    forgery: Number,
    land_vehicle_tech: Number,
    "paint/draw/sculpt": Number,
    paramedic: Number,
    photography_film: Number,
    pick_lock: Number,
    pick_pocket: Number,
    sea_vehicle_tech: Number,
    weapons_tech: Number,
  },
  armor: {
    head: { name: String, sp: Number, penalty: String },
    body: { name: String, sp: Number, penalty: String },
    shield: { name: String, sp: Number, penalty: String },
  },
  weapons: {
    medium_pistol: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    heavy_pistol: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    very_heavy_pistol: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    smg: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    heavy_smg: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    assault_rifle: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    shotgun: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    sniper_rifle: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    bow: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    grenade_launcher: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
    rocket_launcher: {
      equipped: Boolean,
      ammo: Number,
      ammoType: String,
    },
  },
  ammo: {
    m_pistol: {
      basic: Number,
      ap: Number,
      expansive: Number,
      incendiary: Number,
      rubber: Number,
    },
    h_pistol: {
      basic: Number,
      ap: Number,
      expansive: Number,
      incendiary: Number,
      rubber: Number,
    },
    vh_pistol: {
      basic: Number,
      ap: Number,
      expansive: Number,
      incendiary: Number,
      rubber: Number,
    },
    slug: {
      basic: Number,
      ap: Number,
      expansive: Number,
      rubber: Number,
    },
    shells: {
      basic: Number,
      incendiary: Number,
    },
    rifle: {
      basic: Number,
      ap: Number,
      expansive: Number,
      incendiary: Number,
      rubber: Number,
    },
    arrow: {
      basic: Number,
      ap: Number,
      biotoxin: Number,
      expansive: Number,
      incendiary: Number,
      poison: Number,
      rubber: Number,
      sleep: Number,
    },
    grenade: {
      ap: Number,
      biotoxin: Number,
      emp: Number,
      expansive: Number,
      flashbang: Number,
      incendiary: Number,
      poison: Number,
      rubber: Number,
      sleep: Number,
      smoke: Number,
      teargas: Number,
    },
    rocket: {
      ap: Number,
    },
  },
});

module.exports = mongoose.model("Character", simplifiedCharacter);
